"""Harness scenario dataset and data module.

Loads JSONL scenario files from ``harness/scenarios/*.jsonl`` (generated by
``scripts/convert_tau_data.py``).  Each JSONL line maps to one
``EvalDatum(metadata=record)`` so that Trainer and evaluation code can read
the full scenario dict without a custom Datum subclass.

Typical usage::

    from harness.data import HarnessDataModule
    from autopilot.data.datamodule import Stage

    dm = HarnessDataModule('harness/scenarios')
    dm.setup(Stage.fit)
    for batch in dm.train_dataloader():
        print(batch.items[0].metadata['task_id'])
"""

from autopilot.core.types import EvalDatum
from autopilot.data.dataloader import DataLoader
from autopilot.data.datamodule import DataModule, Stage
from autopilot.data.dataset import Dataset
from pathlib import Path
from typing import Any
import json


class HarnessDataset(Dataset):
  """Load harness scenario records from a JSONL file.

  Each non-empty line is one JSON object; ``__getitem__`` wraps the dict as
  ``EvalDatum(metadata=record)`` so Trainer/eval code can read the scenario
  without a custom Datum subclass.
  """

  def __init__(self, path: Path) -> None:
    self._items: list[dict[str, Any]] = []
    text = path.read_text(encoding='utf-8').strip()
    for line in text.split('\n'):
      if line.strip():
        self._items.append(json.loads(line))

  def __getitem__(self, index: int) -> EvalDatum:
    """Return the scenario at ``index`` wrapped as an ``EvalDatum``."""
    item = self._items[index]
    return EvalDatum(metadata=item)

  def __len__(self) -> int:
    """Return the number of scenarios loaded."""
    return len(self._items)


class HarnessDataModule(DataModule):
  """Train/val/test DataLoaders over ``harness/scenarios/*.jsonl``."""

  def __init__(self, scenarios_dir: str, batch_size: int = 1) -> None:
    super().__init__()
    self._dir = Path(scenarios_dir)
    self._batch_size = batch_size

  def setup(self, stage: Stage) -> None:
    """No-op -- datasets are constructed lazily in dataloader factories."""

  def train_dataloader(self) -> DataLoader:
    """Build a DataLoader for the training split."""
    return DataLoader(
      HarnessDataset(self._dir / 'train.jsonl'),
      batch_size=self._batch_size,
    )

  def val_dataloader(self) -> DataLoader:
    """Build a DataLoader for the validation split."""
    return DataLoader(
      HarnessDataset(self._dir / 'val.jsonl'),
      batch_size=self._batch_size,
    )

  def test_dataloader(self) -> DataLoader:
    """Build a DataLoader for the test split."""
    return DataLoader(
      HarnessDataset(self._dir / 'test.jsonl'),
      batch_size=self._batch_size,
    )

  def state_dict(self) -> dict[str, Any]:
    """Serialize scenarios_dir and batch_size for checkpoint round-trips."""
    result = super().state_dict()
    result['scenarios_dir'] = str(self._dir)
    result['batch_size'] = self._batch_size
    return result

  def load_state_dict(self, state: dict[str, Any]) -> None:
    """Restore scenarios_dir and batch_size from a checkpoint."""
    super().load_state_dict(state)
    self._dir = Path(state['scenarios_dir'])
    self._batch_size = int(state['batch_size'])
